package com.lab7.db;

import com.lab7.model.AnalysisRecord;
import com.lab7.model.UserRecord;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class DatabaseManager {
    private static Connection connection;

    private static final String EMBEDDED_URL = "jdbc:h2:file:./data/lab711;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;AUTO_SERVER=TRUE";
    private static final String EMBEDDED_USER = "sa";
    private static final String EMBEDDED_PASSWORD = "";

    public static void connectEmbedded() throws SQLException {
        disconnect();
        connection = DriverManager.getConnection(EMBEDDED_URL, EMBEDDED_USER, EMBEDDED_PASSWORD);
        ensureSchemaAndSeed();
    }

    public static void connect(String url, String user, String password) throws SQLException {
        disconnect();
        connection = DriverManager.getConnection(url, user, password);
        ensureSchemaAndSeed();
    }

    public static Connection getConnection() throws SQLException {
        if (!isConnected()) {
            throw new SQLException("Соединение с базой данных не установлено.");
        }
        return connection;
    }

    public static boolean isConnected() {
        try {
            return connection != null && !connection.isClosed();
        } catch (SQLException e) {
            return false;
        }
    }

    public static void disconnect() {
        try {
            if (connection != null && !connection.isClosed()) {
                connection.close();
            }
        } catch (SQLException ignored) {
        } finally {
            connection = null;
        }
    }

    public static String getDatabaseProductName() {
        if (!isConnected()) {
            return null;
        }

        try {
            DatabaseMetaData metaData = connection.getMetaData();
            return metaData != null ? metaData.getDatabaseProductName() : null;
        } catch (SQLException e) {
            return null;
        }
    }

    public static String getDatabaseName() {
        if (!isConnected()) {
            return null;
        }

        try {
            String catalog = connection.getCatalog();
            return (catalog == null || catalog.isBlank()) ? "lab711" : catalog;
        } catch (SQLException e) {
            return "lab711";
        }
    }

    public static void ensureSchemaAndSeed() throws SQLException {
        Connection con = getConnection();
        con.setAutoCommit(false);
        try (Statement stmt = con.createStatement()) {
            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS users (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        email VARCHAR(255) UNIQUE,
                        plan VARCHAR(32) NOT NULL DEFAULT 'free',
                        role VARCHAR(32) NOT NULL DEFAULT 'user',
                        total_analyses INTEGER NOT NULL DEFAULT 0,
                        is_active BOOLEAN NOT NULL DEFAULT TRUE,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                    )
                    """);

            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS analyses (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        task_id VARCHAR(255) UNIQUE NOT NULL,
                        video_id VARCHAR(255) UNIQUE NOT NULL,
                        user_id INTEGER NOT NULL,
                        source_type VARCHAR(32) NOT NULL,
                        status VARCHAR(32) NOT NULL DEFAULT 'pending',
                        confidence_score DOUBLE NOT NULL DEFAULT 0,
                        has_advertising BOOLEAN NOT NULL DEFAULT FALSE,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_analyses_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
                    )
                    """);
        }

        upsertUser("admin@veritasad.ai", "enterprise", "admin", 24, true);
        upsertUser("analyst@veritasad.ai", "pro", "user", 11, true);
        upsertUser("demo@veritasad.ai", "starter", "user", 3, false);

        int adminId = findUserIdByEmail("admin@veritasad.ai");
        int analystId = findUserIdByEmail("analyst@veritasad.ai");

        upsertAnalysis("task-admin-001", "video-admin-001", adminId, "youtube", "completed", 0.97, true);
        upsertAnalysis("task-analyst-001", "video-analyst-001", analystId, "telegram", "processing", 0.61, true);
        upsertAnalysis("task-analyst-002", "video-analyst-002", analystId, "vk", "pending", 0.18, false);

        con.commit();
        con.setAutoCommit(true);
    }

    private static void upsertUser(String email, String plan, String role, int totalAnalyses, boolean active) throws SQLException {
        String sql = """
                MERGE INTO users (email, plan, role, total_analyses, is_active)
                KEY(email)
                VALUES (?, ?, ?, ?, ?)
                """;
        try (PreparedStatement ps = getConnection().prepareStatement(sql)) {
            ps.setString(1, email);
            ps.setString(2, plan);
            ps.setString(3, role);
            ps.setInt(4, totalAnalyses);
            ps.setBoolean(5, active);
            ps.executeUpdate();
        }
    }

    private static void upsertAnalysis(String taskId, String videoId, int userId, String sourceType,
                                       String status, double confidenceScore, boolean hasAdvertising) throws SQLException {
        String sql = """
                MERGE INTO analyses (task_id, video_id, user_id, source_type, status, confidence_score, has_advertising)
                KEY(task_id)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """;
        try (PreparedStatement ps = getConnection().prepareStatement(sql)) {
            ps.setString(1, taskId);
            ps.setString(2, videoId);
            ps.setInt(3, userId);
            ps.setString(4, sourceType);
            ps.setString(5, status);
            ps.setDouble(6, confidenceScore);
            ps.setBoolean(7, hasAdvertising);
            ps.executeUpdate();
        }
    }

    public static List<UserRecord> getUsers(String emailFilter) throws SQLException {
        String sql = """
                SELECT id,
                       COALESCE(email, '(без email)') AS email,
                       role,
                       plan,
                       total_analyses,
                       is_active,
                       FORMATDATETIME(created_at, 'yyyy-MM-dd HH:mm') AS created_at
                FROM users
                WHERE (? IS NULL OR LOWER(email) LIKE LOWER(?))
                ORDER BY id
                """;

        List<UserRecord> users = new ArrayList<>();
        try (PreparedStatement ps = getConnection().prepareStatement(sql)) {
            String filter = (emailFilter == null || emailFilter.isBlank()) ? null : "%" + emailFilter.trim() + "%";
            ps.setString(1, filter);
            ps.setString(2, filter);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    users.add(new UserRecord(
                            rs.getInt("id"),
                            rs.getString("email"),
                            rs.getString("role"),
                            rs.getString("plan"),
                            rs.getInt("total_analyses"),
                            rs.getBoolean("is_active"),
                            rs.getString("created_at")
                    ));
                }
            }
        }
        return users;
    }

    public static int insertUser(String email, String plan, String role, int totalAnalyses, boolean active) throws SQLException {
        String sql = """
                INSERT INTO users (email, plan, role, total_analyses, is_active)
                VALUES (?, ?, ?, ?, ?)
                """;
        try (PreparedStatement ps = getConnection().prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, email);
            ps.setString(2, plan);
            ps.setString(3, role);
            ps.setInt(4, totalAnalyses);
            ps.setBoolean(5, active);
            ps.executeUpdate();
            try (ResultSet rs = ps.getGeneratedKeys()) {
                if (rs.next()) {
                    return rs.getInt(1);
                }
            }
        }
        throw new SQLException("Не удалось получить ID нового пользователя");
    }

    public static void updateUser(int id, String email, String plan, String role, int totalAnalyses, boolean active) throws SQLException {
        String sql = """
                UPDATE users
                SET email = ?,
                    plan = ?,
                    role = ?,
                    total_analyses = ?,
                    is_active = ?
                WHERE id = ?
                """;
        try (PreparedStatement ps = getConnection().prepareStatement(sql)) {
            ps.setString(1, email);
            ps.setString(2, plan);
            ps.setString(3, role);
            ps.setInt(4, totalAnalyses);
            ps.setBoolean(5, active);
            ps.setInt(6, id);
            ps.executeUpdate();
        }
    }

    public static void deleteUser(int id) throws SQLException {
        try (PreparedStatement ps = getConnection().prepareStatement("DELETE FROM users WHERE id = ?")) {
            ps.setInt(1, id);
            ps.executeUpdate();
        }
    }

    public static List<AnalysisRecord> getAnalysesByUser(int userId) throws SQLException {
        String sql = """
                SELECT id,
                       task_id,
                       video_id,
                       source_type,
                       status,
                       confidence_score,
                       has_advertising,
                       FORMATDATETIME(created_at, 'yyyy-MM-dd HH:mm') AS created_at
                FROM analyses
                WHERE user_id = ?
                ORDER BY id
                """;

        List<AnalysisRecord> records = new ArrayList<>();
        try (PreparedStatement ps = getConnection().prepareStatement(sql)) {
            ps.setInt(1, userId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    records.add(new AnalysisRecord(
                            rs.getInt("id"),
                            rs.getString("task_id"),
                            rs.getString("video_id"),
                            rs.getString("source_type"),
                            rs.getString("status"),
                            rs.getDouble("confidence_score"),
                            rs.getBoolean("has_advertising"),
                            rs.getString("created_at")
                    ));
                }
            }
        }
        return records;
    }

    public static int insertAnalysis(int userId, String taskId, String videoId, String sourceType,
                                     String status, double confidenceScore, boolean hasAdvertising) throws SQLException {
        String sql = """
                INSERT INTO analyses (task_id, video_id, user_id, source_type, status, confidence_score, has_advertising)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """;

        try (PreparedStatement ps = getConnection().prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, taskId);
            ps.setString(2, videoId);
            ps.setInt(3, userId);
            ps.setString(4, sourceType);
            ps.setString(5, status);
            ps.setDouble(6, confidenceScore);
            ps.setBoolean(7, hasAdvertising);
            ps.executeUpdate();
            try (ResultSet rs = ps.getGeneratedKeys()) {
                if (rs.next()) {
                    return rs.getInt(1);
                }
            }
        }
        throw new SQLException("Не удалось получить ID новой аналитики");
    }

    public static void updateAnalysis(int id, String taskId, String videoId, String sourceType,
                                      String status, double confidenceScore, boolean hasAdvertising) throws SQLException {
        String sql = """
                UPDATE analyses
                SET task_id = ?,
                    video_id = ?,
                    source_type = ?,
                    status = ?,
                    confidence_score = ?,
                    has_advertising = ?
                WHERE id = ?
                """;

        try (PreparedStatement ps = getConnection().prepareStatement(sql)) {
            ps.setString(1, taskId);
            ps.setString(2, videoId);
            ps.setString(3, sourceType);
            ps.setString(4, status);
            ps.setDouble(5, confidenceScore);
            ps.setBoolean(6, hasAdvertising);
            ps.setInt(7, id);
            ps.executeUpdate();
        }
    }

    public static void deleteAnalysis(int id) throws SQLException {
        try (PreparedStatement ps = getConnection().prepareStatement("DELETE FROM analyses WHERE id = ?")) {
            ps.setInt(1, id);
            ps.executeUpdate();
        }
    }

    private static int findUserIdByEmail(String email) throws SQLException {
        try (PreparedStatement ps = getConnection().prepareStatement("SELECT id FROM users WHERE email = ?")) {
            ps.setString(1, email);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt(1);
                }
            }
        }
        throw new SQLException("Пользователь не найден: " + email);
    }
}
